import Navbar from '@/components/Shared/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Learn NextJs',
  description: 'Generated by create next app',
}

 const RootLayout=({ children })=> {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
            <Navbar></Navbar>
        </nav>
        {children}
        <footer>

        </footer>
        </body>
    </html>
  )
}
export default RootLayout